(()=>{
const $=id=>document.getElementById(id);
const fmt=n=>{n=Number(n||0);if(n>=1e9)return(n/1e9).toFixed(2)+'B';if(n>=1e6)return(n/1e6).toFixed(2)+'M';if(n>=1e3)return(n/1e3).toFixed(1)+'K';return n.toLocaleString()};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let rows=[],metric='subscribers',range='30';
async function load(){try{const r=await fetch('./data/history/series.json',{cache:'no-store'});if(!r.ok)throw 0;const x=await r.json();rows=Array.isArray(x)?x.sort((a,b)=>a.date.localeCompare(b.date)):[]}catch{rows=[]}render()}
const total=(r,m)=>(r?.channels||[]).reduce((s,c)=>s+Number(c[m]||0),0);
function data(){return range==='all'?rows:rows.slice(-Number(range))}
function draw(){const box=$('historyChart');if(!box)return;const rs=data();if(rs.length<2){box.innerHTML='<div class="empty-history"><b>📈 Building your analytics history</b><br><span>Interactive trend charts appear after at least 2 daily GitHub snapshots.</span></div>';return}
 const vals=rs.map(r=>total(r,metric)), w=900,h=300,p=34,min=Math.min(...vals),max=Math.max(...vals),span=Math.max(max-min,1);const pts=vals.map((v,i)=>{const x=p+(i*(w-p*2))/Math.max(vals.length-1,1),y=h-p-((v-min)/span)*(h-p*2);return[x,y]});const line=pts.map((q,i)=>(i?'L':'M')+q[0].toFixed(1)+' '+q[1].toFixed(1)).join(' ');const area=line+' L '+pts.at(-1)[0].toFixed(1)+' '+(h-p)+' L '+pts[0][0].toFixed(1)+' '+(h-p)+' Z';
 box.innerHTML=`<div class="analytics-chart-wrap"><div class="analytics-y"><span>${fmt(max)}</span><span>${fmt((max+min)/2)}</span><span>${fmt(min)}</span></div><svg class="analytics-svg" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-label="${esc(metric)} trend"><defs><linearGradient id="aGrad" x1="0" x2="1"><stop offset="0%" stop-color="#ff375f"/><stop offset="35%" stop-color="#ff9f0a"/><stop offset="65%" stop-color="#0a84ff"/><stop offset="100%" stop-color="#bf5af2"/></linearGradient><linearGradient id="aFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#0a84ff" stop-opacity=".28"/><stop offset="100%" stop-color="#bf5af2" stop-opacity=".02"/></linearGradient></defs><path class="analytics-area" d="${area}"/><path class="analytics-line" d="${line}"/><g class="analytics-points">${pts.map((q,i)=>`<g class="analytics-point" tabindex="0"><circle cx="${q[0]}" cy="${q[1]}" r="5"></circle><title>${esc(rs[i].date)} • ${fmt(vals[i])} ${esc(metric)}</title></g>`).join('')}</g></svg></div><div class="analytics-foot"><b>${fmt(vals.at(-1))}</b><span>${esc(metric)} • ${rs.length} snapshots • ${esc(rs[0].date)} → ${esc(rs.at(-1).date)}</span></div>`}
function ensureUI(){if($('analyticsIntelligence'))return;const anchor=$('historyChart')?.parentElement;if(!anchor)return;const sec=document.createElement('section');sec.id='analyticsIntelligence';sec.className='glass analytics-intelligence';sec.innerHTML=`<div class="section-head"><div><span class="eyebrow">NETWORK INTELLIGENCE</span><h2>Compare the whole creator network</h2><p>Snapshot-based rankings for subscribers, views, videos and growth.</p></div></div><div class="analytics-kpis" id="analyticsKpis"></div><div class="analytics-ranking"><div class="ranking-head"><h3>Channel ranking</h3><span>Latest snapshot</span></div><div id="analyticsRanking"></div></div>`;anchor.after(sec)}
function renderRanking(){ensureUI();const root=$('analyticsRanking'),k=$('analyticsKpis');if(!root||!k)return;if(!rows.length){root.innerHTML='<div class="analytics-empty">No snapshot data yet.</div>';k.innerHTML='';return}const last=rows.at(-1),first=rows[0];const list=(last.channels||[]).map(c=>{const o=(first.channels||[]).find(x=>x.id===c.id);return{...c,growth:o?Number(c.subscribers)-Number(o.subscribers):null}}).sort((a,b)=>b.subscribers-a.subscribers);const topSub=list[0],topViews=[...list].sort((a,b)=>b.views-a.views)[0],topVideos=[...list].sort((a,b)=>b.videos-a.videos)[0],fast=[...list].filter(x=>x.growth!==null).sort((a,b)=>b.growth-a.growth)[0];k.innerHTML=[['🏆','Top subscribers',topSub?.title,fmt(topSub?.subscribers)],['👀','Top views',topViews?.title,fmt(topViews?.views)],['🎬','Most videos',topVideos?.title,fmt(topVideos?.videos)],['🚀','Fastest growth',fast?.title,fast?((fast.growth>=0?'+':'')+fmt(fast.growth)): 'Collecting']].map(x=>`<div class="analytics-kpi"><span>${x[0]}</span><small>${x[1]}</small><strong>${esc(x[2]||'—')}</strong><b>${esc(x[3])}</b></div>`).join('');const totalSubs=list.reduce((s,x)=>s+x.subscribers,0);root.innerHTML=list.map((c,i)=>`<div class="rank-row"><div class="rank-num">${i+1}</div><div class="rank-name"><strong>${esc(c.title||c.handle)}</strong><span>@${esc(c.handle||'')}</span></div><div class="rank-bar"><i style="width:${topSub?.subscribers?Math.max(4,c.subscribers/topSub.subscribers*100):4}%;background:linear-gradient(90deg,hsl(${i*36},85%,55%),hsl(${i*36+55},85%,58%))"></i></div><div class="rank-stat"><b>${fmt(c.subscribers)}</b><span>${totalSubs?((c.subscribers/totalSubs)*100).toFixed(1):0}% share</span></div><div class="rank-growth ${c.growth>=0?'up':''}">${c.growth===null?'—':(c.growth>=0?'+':'')+fmt(c.growth)}</div></div>`).join('')}
function render(){metric=$('historyMetric')?.value||'subscribers';range=$('historyRange')?.value||'30';draw();renderRanking()}
function injectStyle(){if($('analyticsV2Style'))return;const s=document.createElement('style');s.id='analyticsV2Style';s.textContent=`.analytics-chart-wrap{display:flex;gap:10px;min-height:280px}.analytics-y{width:58px;display:flex;flex-direction:column;justify-content:space-between;font-size:11px;color:#777;padding:10px 0 28px;text-align:right}.analytics-svg{width:100%;height:280px;overflow:visible}.analytics-area{fill:url(#aFill)}.analytics-line{fill:none;stroke:url(#aGrad);stroke-width:4;stroke-linecap:round;stroke-linejoin:round;filter:drop-shadow(0 5px 10px rgba(10,132,255,.2))}.analytics-point circle{fill:#fff;stroke:#0a84ff;stroke-width:3;cursor:pointer;transition:.2s}.analytics-point:hover circle,.analytics-point:focus circle{r:8;stroke:#ff375f}.analytics-foot{display:flex;align-items:baseline;gap:12px;margin:8px 0 0 68px}.analytics-foot b{font-size:25px}.analytics-foot span{color:#777;font-size:12px}.analytics-intelligence{margin-top:18px;padding:24px}.analytics-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.analytics-kpi{padding:16px;border-radius:20px;background:linear-gradient(135deg,rgba(255,255,255,.85),rgba(245,245,247,.55));box-shadow:inset 0 1px rgba(255,255,255,.9);display:grid;gap:4px}.analytics-kpi span{font-size:22px}.analytics-kpi small,.rank-name span,.rank-stat span{color:#777}.analytics-kpi strong{font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.analytics-kpi b{font-size:20px}.ranking-head{display:flex;justify-content:space-between;align-items:center}.ranking-head h3{margin:8px 0}.ranking-head span{font-size:12px;color:#777}.rank-row{display:grid;grid-template-columns:34px minmax(130px,1.2fr) 1fr 100px 75px;gap:12px;align-items:center;padding:12px 0;border-top:1px solid rgba(0,0,0,.07)}.rank-num{font-weight:800;font-size:18px}.rank-name{display:grid}.rank-name strong{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rank-name span{font-size:11px}.rank-bar{height:9px;border-radius:99px;background:#eee;overflow:hidden}.rank-bar i{display:block;height:100%;border-radius:99px}.rank-stat{display:grid;text-align:right}.rank-growth{text-align:right;font-weight:800;color:#ff453a}.rank-growth.up{color:#34c759}.analytics-empty{padding:24px;color:#777}@media(max-width:760px){.analytics-kpis{grid-template-columns:repeat(2,1fr)}.rank-row{grid-template-columns:28px 1fr 72px 52px}.rank-bar{display:none}.rank-stat{font-size:12px}.analytics-intelligence{padding:16px}.analytics-foot{margin-left:40px}.analytics-y{width:38px}}`;document.head.appendChild(s)}
function init(){injectStyle();render();$('historyMetric')?.addEventListener('change',render);$('historyRange')?.addEventListener('change',render);load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
