const API_KEY=window.YOUTUBE_API_KEY||'YOUR_YOUTUBE_DATA_API_KEY';
const channels=[['laxmannepalofficial','Laxman Nepal Official'],['laxmannepalenglish','Laxman Nepal English'],['iamfromhetauda','I Am From Hetauda'],['hamrotechnicalknowledge','Hamro Technical Knowledge'],['laxmannepalvlogs','Laxman Nepal Vlogs'],['lifeoflaxman','Life of Laxman'],['ShreeKathaGhar','Shree Katha Ghar'],['LaxmanLoFi','Laxman LoFi'],['LNN1053','LNN1053'],['TheLaxmanNepal','The Laxman Nepal']];
let data=[],subDesc=false;const $=id=>document.getElementById(id);const fmt=n=>{n=Number(n||0);if(n>=1e9)return(n/1e9).toFixed(2)+'B';if(n>=1e6)return(n/1e6).toFixed(2)+'M';if(n>=1e3)return(n/1e3).toFixed(1)+'K';return n.toLocaleString()};const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,params={}){if(!API_KEY||API_KEY==='YOUR_YOUTUBE_DATA_API_KEY')throw Error('Add your YouTube Data API key');const q=new URLSearchParams({...params,key:API_KEY});const r=await fetch(`https://www.googleapis.com/youtube/v3/${path}?${q}`);if(!r.ok)throw Error((await r.json()).error?.message||'YouTube API request failed');return r.json()}
async function getChannel(handle){const d=await api('channels',{part:'snippet,statistics',forHandle:'@'+handle});return d.items?.[0]||null}
async function load(){ $('lastUpdated').innerHTML='<i></i> Loading live data…';try{data=(await Promise.all(channels.map(async([handle])=>{const c=await getChannel(handle);return c?{id:c.id,handle,title:c.snippet.title,avatar:c.snippet.thumbnails?.high?.url||c.snippet.thumbnails?.default?.url,subs:+c.statistics.subscriberCount||0,views:+c.statistics.viewCount||0,videos:+c.statistics.videoCount||0}:null}))).filter(Boolean);render();$('channelCount').textContent=data.length;$('lastUpdated').innerHTML='<i></i> Live • '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}catch(e){$('lastUpdated').textContent='⚠ '+e.message;toast(e.message)}}
function score(a){if(!a.length)return'—';const s=a.reduce((x,c)=>x+Math.log10(c.subs+1)*45+Math.log10(c.views+1)*25+Math.log10(c.videos+1)*10,0);return Math.min(100,Math.round(s/(a.length*6.2)))+'/100'}
function render(){const subs=data.reduce((a,c)=>a+c.subs,0),views=data.reduce((a,c)=>a+c.views,0),videos=data.reduce((a,c)=>a+c.videos,0);$('totalSubs').textContent=fmt(subs);$('totalViews').textContent=fmt(views);$('totalVideos').textContent=fmt(videos);$('networkScore').textContent=score(data);renderBars();renderDonut();renderCards();renderMonetization()}
function renderBars(){const a=[...data].sort((x,y)=>subDesc?x.subs-y.subs:y.subs-x.subs),max=Math.max(...a.map(x=>x.subs),1);$('subscriberChart').innerHTML=a.map(c=>`<div class="bar-row"><span class="bar-label" title="${esc(c.title)}">${esc(c.title)}</span><span class="bar-track"><span class="bar-fill" style="width:${Math.max(2,Math.sqrt(c.subs/max)*100)}%"></span></span><span class="bar-value">${fmt(c.subs)}</span></div>`).join('')}
function renderDonut(){const a=[...data].sort((x,y)=>y.subs-x.subs),total=a.reduce((x,c)=>x+c.subs,0)||1;let deg=0;const stops=a.map((c,i)=>{const next=deg+c.subs/total*360,s=['#222','#777','#aaa','#ccc','#ddd'][i%5];const z=`${s} ${deg}deg ${next}deg`;deg=next;return z}).join(',');$('shareChart').style.background=`conic-gradient(${stops})`;$('topShare').textContent=Math.round((a[0]?.subs||0)/total*100)+'%';$('shareLegend').innerHTML=a.slice(0,6).map((c,i)=>`<div class="legend-item"><i class="legend-dot" style="opacity:${1-i*.12}"></i><span>${esc(c.title)}</span></div>`).join('')}
function renderCards(){const q=$('searchInput').value.trim().toLowerCase(),sort=$('sortSelect').value;let a=data.filter(c=>(c.title+' '+c.handle).toLowerCase().includes(q));a.sort((x,y)=>sort==='name'?x.title.localeCompare(y.title):y[sort]-x[sort]);$('channelGrid').innerHTML=a.map(c=>`<article class="channel-card glass" onclick="location.href='./channel.html?handle=${encodeURIComponent(c.handle)}'" style="cursor:pointer"><img class="channel-avatar" src="${esc(c.avatar)}" alt=""><div><h3>${esc(c.title)}</h3><span class="handle">@${esc(c.handle)}</span><div class="channel-metrics"><span class="metric"><b>${fmt(c.subs)}</b><span>subs</span></span><span class="metric"><b>${fmt(c.views)}</b><span>views</span></span><span class="metric"><b>${fmt(c.videos)}</b><span>videos</span></span></div></div><a class="open-channel" href="https://www.youtube.com/channel/${encodeURIComponent(c.id)}" target="_blank" rel="noopener" onclick="event.stopPropagation()">↗</a></article>`).join('')||'<div class="loading glass">No matching channels.</div>'}
function renderMonetization(){const top=[...data].sort((a,b)=>b.subs-a.subs)[0],near1000=[...data].filter(c=>c.subs<1000).sort((a,b)=>b.subs-a.subs)[0];if($('monetizationGrid'))$('monetizationGrid').innerHTML=data.map(c=>{const p500=Math.min(100,c.subs/500*100),p1000=Math.min(100,c.subs/1000*100);return`<article class="growth-card glass"><b>${esc(c.title)}</b><span>${fmt(c.subs)} subscribers</span><div class="mini-progress"><i style="width:${p500}%"></i></div><small>500 gate: ${Math.round(p500)}%</small><div class="mini-progress"><i style="width:${p1000}%"></i></div><small>1,000 gate: ${Math.round(p1000)}%</small><a class="text-link" href="./channel.html?handle=${encodeURIComponent(c.handle)}">Open mission →</a></article>`}).join('');if($('monetizationTop'))$('monetizationTop').textContent=top?`${top.title} leads with ${fmt(top.subs)} subscribers.`:'Loading…';if($('monetizationNear'))$('monetizationNear').textContent=near1000?`${near1000.title} is the closest sub-1,000 channel at ${fmt(near1000.subs)}.`:'No channel below 1,000.'}
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2800)}
$('refreshBtn').onclick=load;$('sortSubs').onclick=()=>{subDesc=!subDesc;renderBars()};$('searchInput').oninput=renderCards;$('sortSelect').onchange=renderCards;load();