const API_KEY=window.YOUTUBE_API_KEY||'';
const handles=['laxmannepalofficial','laxmannepalenglish','iamfromhetauda','hamrotechnicalknowledge','laxmannepalvlogs','lifeoflaxman','ShreeKathaGhar','LaxmanLoFi','LNN1053','TheLaxmanNepal'];
const $=id=>document.getElementById(id);const fmt=n=>{n=Number(n||0);if(n>=1e9)return(n/1e9).toFixed(2)+'B';if(n>=1e6)return(n/1e6).toFixed(2)+'M';if(n>=1e3)return(n/1e3).toFixed(1)+'K';return n.toLocaleString()};
async function api(handle){if(!API_KEY)throw Error('Live API unavailable');const q=new URLSearchParams({part:'snippet,statistics',forHandle:'@'+handle,key:API_KEY});const r=await fetch('https://www.googleapis.com/youtube/v3/channels?'+q);if(!r.ok)throw Error('Live API request failed');return r.json()}
async function snapshot(){const r=await fetch('./data/current.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Snapshot unavailable');return r.json()}
async function history(){const r=await fetch('./data/history/series.json?ts='+Date.now(),{cache:'no-store'});return r.ok?r.json():[]}
const handle=new URLSearchParams(location.search).get('handle')||handles[0];
async function load(){let c=null,mode='snapshot';try{const live=await api(handle);c=live.items?.[0]||null;if(c)mode='live'}catch(e){}let snap=null,hist=[];try{snap=await snapshot();hist=await history()}catch(e){}if(!c){c=(snap?.channels||[]).find(x=>x.handle===handle);if(!c)throw Error('Channel data unavailable')}render(c,Array.isArray(hist)?hist:[],mode)}
function render(c,history,mode){const s=c.statistics||c,subs=+s.subscriberCount||+c.subscribers||0,views=+s.viewCount||+c.views||0,videos=+s.videoCount||+c.videos||0;const latest=history.at?.(-1)||history[history.length-1];const network=(latest?.channels||[]).length?(latest.channels.reduce((a,x)=>a+(+x.subscribers||0),0)):subs;const rows=(latest?.channels||[]).slice().sort((a,b)=>(+b.subscribers||0)-(+a.subscribers||0));const rank=rows.findIndex(x=>x.id===c.id)+1;$('avatar').src=c.snippet?.thumbnails?.high?.url||c.snippet?.thumbnails?.default?.url||c.thumbnail||'';$('title').textContent=c.snippet?.title||c.title||handle;$('handle').textContent='@'+handle;$('youtube').href='https://www.youtube.com/channel/'+encodeURIComponent(c.id);$('subs').textContent=fmt(subs);$('views').textContent=fmt(views);$('videos').textContent=fmt(videos);$('share').textContent=network?((subs/network)*100).toFixed(1)+'%':'';$('rank').textContent=rank?`#${rank} of ${rows.length} channels by subscribers`:'Rank unavailable';$('mode').textContent=mode==='live'?'LIVE • YouTube API':'SNAPSHOT • GitHub';goal('500',subs,500);goal('1000',subs,1000);const h=history.filter(r=>(r.channels||[]).some(x=>x.id===c.id)).sort((a,b)=>a.date.localeCompare(b.date));const first=h[0]?.channels?.find(x=>x.id===c.id),last=h.at(-1)?.channels?.find(x=>x.id===c.id);const delta=first&&last?(+last.subscribers||0)-(+first.subscribers||0):0;$('growth').textContent=h.length>1?`${delta>=0?'+':''}${fmt(delta)} subscribers since ${h[0].date}`:'Daily snapshots will build growth history.';$('gap').textContent=subs>=1000?'1,000 subscriber gate reached 🎉':`${fmt(1000-subs)} subscribers to 1,000`;$('focus').textContent=subs<500?'Primary focus: reach 500 subscribers with consistent, repeatable content.':subs<1000?'Primary focus: convert viewers into subscribers and push toward 1,000.':'Primary focus: qualified watch hours, Shorts performance and YPP readiness.';$('efficiency').textContent=videos?fmt(views/videos)+' views/video':'—';draw(h,c.id)}
function goal(k,subs,target){const p=Math.min(100,subs/target*100);$('goal'+k).textContent=Math.round(p)+'%';$('bar'+k).style.width=p+'%';$('meta'+k).textContent=`${fmt(subs)} / ${fmt(target)} subscribers`}
function draw(history,id){const points=history.map(r=>{const c=(r.channels||[]).find(x=>x.id===id);return c?{date:r.date,v:+c.subscribers||0}:null}).filter(Boolean);if(points.length<2){$('chartState').textContent='Not enough saved snapshots yet.';return}$('chartState').textContent=`${points.length} saved snapshots • subscriber history`;const svg=$('chart'),W=900,H=240,p=18,vals=points.map(x=>x.v),min=Math.min(...vals),max=Math.max(...vals),span=Math.max(max-min,1),xy=(v,i)=>[p+i*(W-p*2)/Math.max(points.length-1,1),H-p-(v-min)/span*(H-p*2)],line=points.map((x,i)=>xy(x.v,i).join(',')).join(' ');svg.innerHTML=`<polyline points="${line}" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><text x="18" y="22" fill="currentColor" opacity=".55">${fmt(max)}</text><text x="18" y="230" fill="currentColor" opacity=".55">${fmt(min)}</text>`}
load().catch(e=>{$('title').textContent='Unable to load';$('handle').textContent=e.message;$('mode').textContent='ERROR'})
