const API_KEY=window.YOUTUBE_API_KEY||'YOUR_YOUTUBE_DATA_API_KEY';
const handles=['laxmannepalofficial','laxmannepalenglish','iamfromhetauda','hamrotechnicalknowledge','laxmannepalvlogs','lifeoflaxman','ShreeKathaGhar','LaxmanLoFi','LNN1053','TheLaxmanNepal'];
const $=id=>document.getElementById(id);const fmt=n=>{n=Number(n||0);if(n>=1e9)return(n/1e9).toFixed(2)+'B';if(n>=1e6)return(n/1e6).toFixed(2)+'M';if(n>=1e3)return(n/1e3).toFixed(1)+'K';return n.toLocaleString()};
async function api(path,params={}){const q=new URLSearchParams({...params,key:API_KEY});const r=await fetch(`https://www.googleapis.com/youtube/v3/${path}?${q}`);if(!r.ok)throw Error('YouTube API request failed');return r.json()}
const handle=new URLSearchParams(location.search).get('handle')||handles[0];
async function load(){try{const [live,hist]=await Promise.all([api('channels',{part:'snippet,statistics',forHandle:'@'+handle}),fetch('./data/history/series.json',{cache:'no-store'}).then(r=>r.ok?r.json():[]).catch(()=>[])]);const c=live.items?.[0];if(!c)throw Error('Channel not found');const s=c.statistics||{},all=(await api('channels',{part:'statistics',id:handles.map(()=>null).filter(Boolean).join(',')})).items||[];render(c,hist)}catch(e){$('title').textContent='Unable to load';$('handle').textContent=e.message}}
function render(c,history){const s=c.statistics||{},subs=+s.subscriberCount||0,views=+s.viewCount||0,videos=+s.videoCount||0;const latest=history.at?.(-1)||history[history.length-1];const totals=(latest?.channels||[]).filter(x=>x.id===c.id)[0];const networkSubs=(latest?.channels||[]).reduce((a,x)=>a+(+x.subscribers||0),0)||subs;const rows=(latest?.channels||[]).slice().sort((a,b)=>(+b.subscribers||0)-(+a.subscribers||0));const rank=rows.findIndex(x=>x.id===c.id)+1;$('avatar').src=c.snippet?.thumbnails?.high?.url||c.snippet?.thumbnails?.default?.url||'';$('title').textContent=c.snippet?.title||handle;$('handle').textContent='@'+handle;$('youtube').href='https://www.youtube.com/channel/'+encodeURIComponent(c.id);$('subs').textContent=fmt(subs);$('views').textContent=fmt(views);$('videos').textContent=fmt(videos);$('share').textContent=((subs/networkSubs)*100).toFixed(1)+'%';$('rank').textContent=rank?`#${rank} of ${rows.length||10} channels by subscribers`:'';goal('500',subs,500);goal('1000',subs,1000);const h=history.filter(r=>(r.channels||[]).some(x=>x.id===c.id)).sort((a,b)=>a.date.localeCompare(b.date));const first=h[0]?.channels?.find(x=>x.id===c.id);const last=h.at(-1)?.channels?.find(x=>x.id===c.id);const delta=first&&last?(+last.subscribers||0)-(+first.subscribers||0):0;$('growth').textContent=h.length>1?`${delta>=0?'+':''}${fmt(delta)} subscribers since ${h[0].date}`:'History is still collecting.';$('gap').textContent=subs>=1000?'1,000 subscriber gate reached 🎉':`${fmt(Math.max(1000-subs,0))} subscribers to the 1,000 gate.`;$('focus').textContent=subs<500?'Reach 500 first: publish consistently and build returning viewers.':subs<1000?'500 reached/near: push toward 1,000 while checking Studio watch-hours.':'Subscriber gate reached — focus on qualified watch hours, Shorts views and policy readiness.';draw(h,c.id)}
function goal(k,subs,target){const p=Math.min(100,subs/target*100);$('goal'+k).textContent=Math.round(p)+'%';$('bar'+k).style.width=p+'%';$('meta'+k).textContent=`${fmt(subs)} / ${fmt(target)} subscribers`}
function draw(history,id){const points=history.map(r=>{const c=(r.channels||[]).find(x=>x.id===id);return c?{date:r.date,v:+c.subscribers||0}:null}).filter(Boolean);if(points.length<2){$('chartState').textContent='Not enough saved snapshots yet. Daily GitHub snapshots will build this chart.';return}$('chartState').textContent=`${points.length} saved snapshots • subscriber history`;const svg=$('chart'),W=900,H=240,p=18,vals=points.map(x=>x.v),min=Math.min(...vals),max=Math.max(...vals),span=Math.max(max-min,1);const xy=(v,i)=>[p+i*(W-p*2)/Math.max(points.length-1,1),H-p-(v-min)/span*(H-p*2)];const line=points.map((x,i)=>xy(x.v,i).join(',')).join(' ');svg.innerHTML=`<polyline points="${line}" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><text x="18" y="22" fill="currentColor" opacity=".55">${fmt(max)}</text><text x="18" y="230" fill="currentColor" opacity=".55">${fmt(min)}</text>`}
load();