(() => {
  const $=id=>document.getElementById(id);
  const fmt=n=>{n=Number(n||0);if(n>=1e9)return(n/1e9).toFixed(2)+'B';if(n>=1e6)return(n/1e6).toFixed(2)+'M';if(n>=1e3)return(n/1e3).toFixed(1)+'K';return n.toLocaleString()};
  const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const avatar=c=>window.avatarMarkup?window.avatarMarkup(c,'compare-avatar'):`<span class="avatar-shell compare-avatar-shell"><span class="avatar-fallback">${esc((c.title||c.handle||'?').trim().charAt(0).toUpperCase()||'?')}</span></span>`;
  let selected=[],metric='subs';
  const palette=['#ff375f','#ff9f0a','#34c759','#0a84ff','#5e5ce6','#bf5af2','#64d2ff','#30d158','#ff453a','#ffd60a'];
  const getData=()=>Array.isArray(window.youtubeNetworkData)?window.youtubeNetworkData:[];
  function styles(){if($('comparisonStyles'))return;const s=document.createElement('style');s.id='comparisonStyles';s.textContent=`#comparison{scroll-margin-top:90px}.comparison-card{padding:18px}.compare-toolbar{display:flex;gap:14px;align-items:flex-start;justify-content:space-between;flex-wrap:wrap}.compare-picker{display:flex;gap:8px;flex-wrap:wrap;flex:1;min-width:240px}.compare-chip{display:flex;align-items:center;gap:7px;padding:7px 10px;border:1px solid rgba(0,0,0,.07);border-radius:999px;background:rgba(255,255,255,.48);cursor:pointer;font-size:11px;transition:.2s}.compare-chip:hover,.compare-chip.selected{background:rgba(255,255,255,.88);transform:translateY(-1px)}.compare-chip input{accent-color:#111}.compare-chip .avatar-shell,.compare-channel .avatar-shell{width:28px;height:28px}.compare-bar-name .avatar-shell{width:28px;height:28px}.compare-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.compare-actions select{border:1px solid rgba(0,0,0,.1);border-radius:12px;padding:9px 11px;background:rgba(255,255,255,.7);font:inherit;font-size:12px}.comparison-bars{display:grid;gap:10px;margin:22px 0}.compare-bar-row{display:grid;grid-template-columns:minmax(170px,1.2fr) minmax(100px,3fr) 75px;gap:12px;align-items:center}.compare-bar-name{display:flex;align-items:center;gap:8px;min-width:0;font-size:12px;font-weight:700}.compare-bar-name>span:last-child{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.compare-rank{width:18px;color:#777;font-size:10px}.compare-track{height:12px;border-radius:99px;background:rgba(0,0,0,.06);overflow:hidden}.compare-track i{display:block;height:100%;border-radius:99px;min-width:3px}.compare-bar-row>b{text-align:right;font-size:13px}.comparison-table-wrap{overflow-x:auto;border-radius:16px}.comparison-table{width:100%;border-collapse:collapse;min-width:760px;font-size:12px}.comparison-table th,.comparison-table td{padding:12px 10px;text-align:right;border-top:1px solid rgba(0,0,0,.07);white-space:nowrap}.comparison-table th:first-child,.comparison-table td:first-child{text-align:left}.comparison-table th{font-size:10px;text-transform:uppercase;letter-spacing:.05em;color:#777}.compare-channel{display:flex;align-items:center;gap:8px;min-width:190px}.compare-channel>span{display:grid;min-width:0}.compare-channel strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.compare-channel small{color:#777;font-size:9px}.compare-channel em{font-style:normal;font-size:8px;padding:4px 6px;border-radius:99px;background:rgba(255,159,10,.16);color:#a66300;margin-left:auto}.comparison-table tbody tr:hover{background:rgba(255,255,255,.35)}@media(max-width:650px){.comparison-card{padding:12px}.compare-bar-row{grid-template-columns:1fr 80px}.compare-bar-row>b{grid-column:2}.compare-bar-row .compare-track{grid-column:1/-1;grid-row:2}.compare-actions{width:100%}.compare-actions select{flex:1}.compare-picker{min-width:100%}}`;document.head.appendChild(s)}
  function inject(){if($('comparison'))return;const anchor=$('dataBreakdown')||$('channels');if(!anchor)return;const section=document.createElement('section');section.className='section';section.id='comparison';section.innerHTML=`<div class="section-heading"><div><p class="eyebrow">NETWORK COMPARISON</p><h2>Compare channels side by side.</h2><p>Select channels and change the metric to see the gaps clearly.</p></div><span id="compareCount" class="api-badge">0 selected</span></div><article class="comparison-card glass"><div class="compare-toolbar"><div id="comparePicker" class="compare-picker"></div><div class="compare-actions"><select id="compareMetric"><option value="subs">Subscribers</option><option value="views">Views</option><option value="videos">Videos</option><option value="viewsPerVideo">Views / video</option><option value="subsPerVideo">Subscribers / video</option></select><button id="compareAll" class="mini-button" type="button">Select all</button><button id="compareClear" class="mini-button" type="button">Clear</button></div></div><div id="compareBars" class="comparison-bars"></div><div class="comparison-table-wrap"><table class="comparison-table"><thead><tr><th>Channel</th><th>Subscribers</th><th>Views</th><th>Videos</th><th>Views/video</th><th>Subs/video</th><th>Gap to leader</th></tr></thead><tbody id="compareRows"></tbody></table></div></article>`;anchor.after(section);$('compareMetric').addEventListener('change',e=>{metric=e.target.value;draw()});$('compareAll').addEventListener('click',()=>{selected=getData().map(c=>c.handle);draw()});$('compareClear').addEventListener('click',()=>{selected=[];draw()});draw()}
  function picker(){const box=$('comparePicker');if(!box)return;box.innerHTML=getData().map(c=>`<label class="compare-chip ${selected.includes(c.handle)?'selected':''}"><input type="checkbox" value="${esc(c.handle)}" ${selected.includes(c.handle)?'checked':''}>${avatar(c)}<span>${esc(c.title)}</span></label>`).join('');box.querySelectorAll('input').forEach(input=>input.addEventListener('change',e=>{const h=e.target.value;if(e.target.checked){if(!selected.includes(h))selected.push(h)}else selected=selected.filter(x=>x!==h);draw()}))}
  function value(c){return Number(metric==='subs'?c.subs:metric==='views'?c.views:metric==='videos'?c.videos:metric==='viewsPerVideo'?c.views/Math.max(1,c.videos):c.subs/Math.max(1,c.videos))||0}
  function draw(){const all=getData();if(!all.length)return;if(!selected.length)selected=all.slice(0,Math.min(4,all.length)).map(c=>c.handle);const rows=all.filter(c=>selected.includes(c.handle)).sort((a,b)=>value(b)-value(a));const max=Math.max(...rows.map(value),1),leader=rows[0];if($('compareCount'))$('compareCount').textContent=`${rows.length} selected`;picker();if($('compareBars'))$('compareBars').innerHTML=rows.map((c,i)=>`<div class="compare-bar-row"><div class="compare-bar-name"><span class="compare-rank">${i+1}</span>${avatar(c)}<span>${esc(c.title)}</span></div><div class="compare-track"><i style="width:${Math.max(3,value(c)/max*100)}%;background:${palette[i%palette.length]}"></i></div><b>${fmt(value(c))}</b></div>`).join('');if($('compareRows'))$('compareRows').innerHTML=rows.map((c,i)=>{const vp=c.views/Math.max(1,c.videos),sp=c.subs/Math.max(1,c.videos),gap=Math.max(0,value(leader)-value(c));return`<tr><td><div class="compare-channel">${avatar(c)}<span><strong>${esc(c.title)}</strong><small>@${esc(c.handle)}</small></span>${i===0?'<em>LEADER</em>':''}</div></td><td>${fmt(c.subs)}</td><td>${fmt(c.views)}</td><td>${fmt(c.videos)}</td><td>${fmt(vp)}</td><td>${sp.toFixed(2)}</td><td>${i===0?'—':fmt(gap)}</td></tr>`}).join('')}
  function boot(){styles();inject();const observer=new MutationObserver(()=>{if(getData().length)inject()});observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>{if(getData().length){selected=getData().slice(0,4).map(c=>c.handle);draw()}},700)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();