(()=>{
const $=id=>document.getElementById(id);
const fmt=n=>{n=Number(n||0);const sign=n<0?'-':'';n=Math.abs(n);if(n>=1e9)return sign+(n/1e9).toFixed(2)+'B';if(n>=1e6)return sign+(n/1e6).toFixed(2)+'M';if(n>=1e3)return sign+(n/1e3).toFixed(1)+'K';return sign+n.toLocaleString()};
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
let rows=[];
function channelGrowth(c,days){if(rows.length<2)return null;const end=rows.at(-1), cutoff=new Date(end.date);cutoff.setDate(cutoff.getDate()-days);let start=rows.find(r=>new Date(r.date)>=cutoff)||rows[0];const a=(start.channels||[]).find(x=>x.id===c.id||x.handle===c.handle);const b=(end.channels||[]).find(x=>x.id===c.id||x.handle===c.handle);if(!a||!b)return null;return{delta:Number(b.subscribers||0)-Number(a.subscribers||0),from:start.date,to:end.date};}
function render(){const data=window.youtubeNetworkData||[];if(!data.length)return;let anchor=$('channelGrid');if(!anchor)return;let sec=$('growthIntelligence');if(!sec){sec=document.createElement('section');sec.id='growthIntelligence';sec.className='section growth-intelligence';anchor.closest('.section')?.after(sec);}
const cards=data.map(c=>{const g7=channelGrowth(c,7),g30=channelGrowth(c,30),g90=channelGrowth(c,90);const perDay=g30&&g30.delta?g30.delta/Math.max(1,(new Date(g30.to)-new Date(g30.from))/86400000):0;const pct=g30&&Number(c.subs)?g30.delta/(Number(c.subs)-g30.delta||1)*100:null;const target=c.subs<500?500:1000;const gap=Math.max(0,target-c.subs);return{c,g7,g30,g90,perDay,pct,gap,target}});
const fastest=[...cards].filter(x=>x.g30).sort((a,b)=>b.g30.delta-a.g30.delta)[0];
sec.innerHTML=`<div class="section-heading"><div><p class="eyebrow">CREATOR INTELLIGENCE</p><h2>Growth by channel.</h2><p>Compare subscriber movement across your saved daily snapshots.</p></div><span class="api-badge">${rows.length} snapshots</span></div><div class="growth-v3-grid">${cards.map(x=>`<article class="growth-v3-card glass"><div class="growth-v3-head"><div><strong>${esc(x.c.title)}</strong><span>@${esc(x.c.handle)}</span></div><b>${fmt(x.c.subs)}</b></div><div class="growth-v3-stats"><div><small>7D</small><strong class="${x.g7?.delta>=0?'positive':''}">${x.g7?((x.g7.delta>=0?'+':'')+fmt(x.g7.delta)):'—'}</strong></div><div><small>30D</small><strong class="${x.g30?.delta>=0?'positive':''}">${x.g30?((x.g30.delta>=0?'+':'')+fmt(x.g30.delta)):'—'}</strong></div><div><small>90D</small><strong class="${x.g90?.delta>=0?'positive':''}">${x.g90?((x.g90.delta>=0?'+':'')+fmt(x.g90.delta)):'—'}</strong></div></div><div class="growth-v3-bar"><i style="width:${Math.min(100,Math.max(0,(x.c.subs/x.target)*100))}%"></i></div><div class="growth-v3-foot"><span>${x.c.subs>=1000?'1K reached 🎉':`${fmt(x.gap)} to ${fmt(x.target)}`}</span><span>${x.g30?.delta?`${fmt(Math.round(x.perDay))}/day avg`:rows.length<2?'Collecting history':'No change'}</span></div><a href="./channel.html?handle=${encodeURIComponent(x.c.handle)}">Open channel →</a></article>`).join('')}</div><div class="growth-v3-summary glass"><span>🚀 Current 30-day movement</span><strong>${fastest?esc(fastest.c.title):'Collecting data'}</strong><b>${fastest?((fastest.g30.delta>=0?'+':'')+fmt(fastest.g30.delta)+' subscribers'): 'Need at least 2 snapshots'}</b></div>`}
async function load(){try{const r=await fetch('./data/history/series.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw 0;const x=await r.json();rows=Array.isArray(x)?x.sort((a,b)=>a.date.localeCompare(b.date)):[]}catch{rows=[]}render()}
function style(){if($('growthV3Style'))return;const s=document.createElement('style');s.id='growthV3Style';s.textContent=`.growth-intelligence{padding-top:10px}.growth-v3-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.growth-v3-card{padding:20px;border-radius:24px}.growth-v3-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.growth-v3-head div{min-width:0;display:grid;gap:3px}.growth-v3-head strong{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.growth-v3-head span{font-size:11px;color:#777}.growth-v3-head>b{font-size:24px;white-space:nowrap}.growth-v3-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:18px 0}.growth-v3-stats div{padding:11px;border-radius:16px;background:rgba(255,255,255,.55);display:grid;gap:3px}.growth-v3-stats small{color:#777;font-size:10px}.growth-v3-stats strong{font-size:17px}.growth-v3-stats .positive{color:#34c759}.growth-v3-bar{height:8px;border-radius:99px;background:rgba(0,0,0,.08);overflow:hidden}.growth-v3-bar i{display:block;height:100%;border-radius:99px;background:linear-gradient(90deg,#ff375f,#0a84ff,#bf5af2)}.growth-v3-foot{display:flex;justify-content:space-between;gap:10px;font-size:11px;color:#777;margin:8px 0 12px}.growth-v3-card>a{font-weight:800;text-decoration:none;color:inherit;font-size:12px}.growth-v3-summary{margin-top:14px;padding:18px;display:flex;align-items:center;gap:14px;flex-wrap:wrap}.growth-v3-summary span{color:#777}.growth-v3-summary strong{font-size:15px}.growth-v3-summary b{margin-left:auto;font-size:18px}@media(max-width:700px){.growth-v3-grid{grid-template-columns:1fr}.growth-v3-summary b{margin-left:0;width:100%}}`;document.head.appendChild(s)}
function init(){style();window.addEventListener('youtube-data-ready',render);load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
