(()=>{
const $=id=>document.getElementById(id),fmt=n=>{n=Number(n||0);if(n>=1e9)return(n/1e9).toFixed(2)+'B';if(n>=1e6)return(n/1e6).toFixed(2)+'M';if(n>=1e3)return(n/1e3).toFixed(1)+'K';return n.toLocaleString()},history=[];
const total=(r,m)=>(r?.channels||[]).reduce((s,c)=>s+Number(c[m]||0),0);
const snap=(date)=>{let best=null,d=Infinity;history.forEach(r=>{const x=Math.abs(new Date(r.date)-date);if(x<d){d=x;best=r}});return best};
function growth(days){if(history.length<2)return null;const last=history.at(-1),d=new Date(last.date);d.setUTCDate(d.getUTCDate()-days);const old=snap(d);if(!old||old.date===last.date)return null;const a=total(last,'subscribers'),b=total(old,'subscribers');return{delta:a-b,pct:b?(a-b)/b:0,date:old.date}}
function setGrowth(id,meta,r){if(!r){$(id).textContent='—';$(meta).textContent='Collecting snapshots';return}$(id).textContent=(r.delta>=0?'+':'')+fmt(r.delta);$(meta).textContent=`${(r.pct*100).toFixed(2)}% since ${r.date}`}
function render(){setGrowth('growth7','growth7Meta',growth(7));setGrowth('growth30','growth30Meta',growth(30));setGrowth('growth90','growth90Meta',growth(90));if(history.length<2){$('historyStatus').textContent=history.length+' snapshot'+(history.length===1?'':'s');$('fastestChannel').textContent='—';$('fastestChannelMeta').textContent='Needs 2+ snapshots';return}$('historyStatus').textContent=history.length+' snapshots';const first=history[0],last=history.at(-1),rank=(last.channels||[]).map(c=>{const o=(first.channels||[]).find(x=>x.id===c.id);return{c,d:o?c.subscribers-o.subscribers:0}}).sort((a,b)=>b.d-a.d)[0];$('fastestChannel').textContent=rank?.c?.title||'—';$('fastestChannelMeta').textContent=rank?`${rank.d>=0?'+':''}${fmt(rank.d)} subscribers since ${first.date}`:'—';draw()}
function draw(){const box=$('historyChart'),metric=$('historyMetric').value,range=$('historyRange').value,rows=range==='all'?history:history.slice(-Number(range));if(!rows.length){box.innerHTML='<div class="empty-history">No saved snapshots yet. The daily GitHub Action will populate this automatically.</div>';return}const vals=rows.map(r=>total(r,metric)),min=Math.min(...vals),max=Math.max(...vals),span=Math.max(max-min,1);box.innerHTML=`<div class="history-axis"><span>${fmt(max)}</span><span>${fmt(min)}</span></div><div class="history-bars">${rows.map((r,i)=>{const h=Math.max(5,((vals[i]-min)/span)*100);return`<div class="history-point" title="${r.date}: ${fmt(vals[i])}"><span style="height:${h}%"></span><small>${r.date.slice(5)}</small></div>`}).join('')}</div><div class="history-summary"><strong>${fmt(vals.at(-1))}</strong><span>${metric} total • ${rows.length} snapshot${rows.length===1?'':'s'}</span></div>`}
async function load(){try{const r=await fetch('./data/history/series.json',{cache:'no-store'});if(!r.ok)throw 0;const x=await r.json();history=Array.isArray(x)?x.sort((a,b)=>a.date.localeCompare(b.date)):[]}catch{history=[]}render()}
$('historyMetric').onchange=draw;$('historyRange').onchange=draw;load();
})();
